config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contactus' =>'pages#contactus'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base

validates :title ,presence: true, length: {minimum: 5,maximum: 50}
  validates :description , presence: true , length: {minimum: 10,maximum: 300 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController <ApplicationController
def new
@article= Article.new

end
  def create

    #render :plain => params[:article].inspect
    @article= Article.new(article_params)
    if @article.save
    #do something
    flash[:notice]="Article successfuly created"
    redirect_to article_path(@article)
  else
      render 'new'
    end
  end

def show
  @article=Article.find(params[:id])
end


  private
def article_params
  params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def contactus
  	
  end



end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<div class="container">
  <%if @article.errors.any? %>
    <ul>
    <% @article.errors.full_messages.each do|msg| %>

    <li><%=msg %></li>
    <% end %>
    </ul>
  <%end %>



<h1>this is article posting page</h1>

<%=form_for @article do |s| %>

<p>

  <%= s.label :title %> <br>
<%=s.text_field :title %>

</p>

<p>

  <%=s.label :description %><br>

  <%= s.text_area :description %>

</p>
<p>
  <%=s.submit %>

</p>

<%end %>
</div>
</body>
</html>

app/views/articles/show.html.erb
<h1>showing selected article</h1>
<p>
  Title:<%=@article.title %>

</p>
<p>

  Description:<%=@article.description %>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omruby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        

        <%= link_to root_path do %>
        <%= content_tag :span, "Home", :class => "nav-link" %>
        <% end %>
        <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      </li>
      <li class="nav-item">
        <%= link_to about_path do %>
        <%= content_tag :span, "About US", :class => "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
       <%= link_to contactus_path do %>
        <%= content_tag :span, "CONTACT US", :class => "nav-link" %>
        <% end %>
      
      
  
    
      <li class="nav-item">
       <%= link_to root_path do %>
        <%= content_tag :span, "SignUP", :class => "nav-link" %>
        <% end %>
      </li>
    
    <li class="nav-item">
        <%= link_to root_path do %>
        <%= content_tag :span, "SignIN", :class => "nav-link" %>
        <% end %>
      </li>
        </ul>
  </div>
</nav>



     <% flash.each do|name, msg| %>

      <ul>
        <li>
          <%= msg %>
        </li>

      </ul>


    <% end %>
    <!-- Page Content -->
    <%= yield %>
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© first running app</p>
        </center>
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contactus.html.erb
<div class="jumbotron">
	<div class="container">
	<h2> this is the contact us page</h2>
<p>this is the contact us page and here we are generating information to make changes

feel free to contact with me on my email address <h3>engineer.mshehzad@gmail.com</h3>
</p>
</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to my website!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>